# Generated by Django 4.2.2 on 2023-06-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0002_rename_item_itemmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='meal_type',
            field=models.CharField(choices=[('starters', 'Starters'), ('salads', 'Salads'), ('main_course', 'Main Course'), ('desserts', 'Desserts'), ('drinks', 'Drinks')], max_length=200),
        ),
    ]
